import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import 'react-vertical-timeline-component/style.min.css';
import './globals.css'
import { Roboto  } from 'next/font/google'
// import { SSRProvider } from '@/components/ReactBootstrap';
import { ToastContainer } from '@/components/ReactBootstrap';
import { AuthProvider } from '@/context/AuthContext';
import { ChatProvider } from '@/context/ChatContext';

const roboto = Roboto ({ weight:['100','300','400','500','700','900'],subsets: ['latin'] })

export const metadata = {
  title: 'PTOP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <ChatProvider>
      <body className={roboto.className}>

        {children}
        <ToastContainer autoClose='1000'/>
        
      </body>
      </ChatProvider>
      </AuthProvider>
    </html>
  )
}
