import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css'
import { Poppins  } from 'next/font/google'
// import { SSRProvider } from '@/components/ReactBootstrap';
import { ToastContainer } from '@/components/ReactBootstrap';
import { AuthProvider } from '@/context/AuthContext';
import { ChatProvider } from '@/context/ChatContext';

const poppins = Poppins ({ weight:['100','200','300','400','500','600','700','800','900'],subsets: ['latin'] })

export const metadata = {
  title: 'PTOP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <ChatProvider>
      <body className={poppins.className}>

        {children}
        <ToastContainer/>
        
      </body>
      </ChatProvider>
      </AuthProvider>
    </html>
  )
}
